### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by mschwartz** [evandcoleman/node-appletv#37] opened 2020-02-10 15:41 UTC
https://evandcoleman.github.io/node-appletv/

Was looking for documentation for the API to get artwork.  This link does show a home/index page, but the links I tried render 404 pages.

Thanks for the awesome plugin and for working on it.

**Comment by evandcoleman** [comment] 2020-02-10 22:52
Duplicate of #9.

**Closed by evandcoleman** 2020-02-10 22:52 UTC
